#!/usr/bin/env python3
#Code generated by ChatGPT 5 on 10/3/2025 by Laurie Lyon
# with minor manual edits for style and clarity
"""
Generate poster panels for a single ordered OTU pair (i, j):
- Panel B: real time series of OTUj (driver) and OTUi (responder)
- Panel C: IAAFT surrogates of j (3 examples) vs original j
- Panel D: surrogate histogram with rho_obs and two-tailed p

Matches the user's pipeline:
  - Statistic: Spearman( j_t , Δi_{t+1} )
  - Null: IAAFT surrogates of j (driver) preserving amplitude distribution and spectrum
  - i is held fixed to preserve real response dynamics
  - Two-tailed p from |rho_surr| >= |rho_obs| with +1 pseudocount

Example:
  python make_poster_panels_for_pair.py \
    --biom_file biom.csv \
    --meta_file meta.csv \
    --otu_j 3609545 \
    --otu_i 4346675 \
    --n_surr 500 \
    --n_iter 20 \
    --outdir panels_pair_3609545_4346675
"""

import argparse
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# Import your class + warning context from your module
from timeseries_0625_update import MiBiTimeSeries


def two_tailed_p_from_surrogates(rho_obs: float, surr_rhos: np.ndarray) -> float:
    """Two-tailed p with +1 pseudocount for stability."""
    return (np.sum(np.abs(surr_rhos) >= abs(rho_obs)) + 1) / (len(surr_rhos) + 1)


def export_panel_B_time_series(ts: MiBiTimeSeries, i_id: str, j_id: str,
                               out: Path, dpi: int = 300):
    """Real time series of j (driver) and i (responder)."""
    j = ts.biom.loc[j_id].values
    i = ts.biom.loc[i_id].values
    t = np.arange(ts.biom.shape[1])

    for ext in ("png", "svg"):
        plt.figure(figsize=(9, 3))
        plt.plot(t, j, lw=2, color = 'red', label=f"{j_id} (OTUj)")
        plt.plot(t, i, lw=2, color = 'blue', label=f"{i_id} (OTUi)")
        plt.xlabel("Time (aligned index)")
        plt.ylabel("CLR Relative Abundance")
        plt.title("Time series used for TLC")
        plt.legend()
        plt.tight_layout()
        plt.savefig(out / f"panel_B_time_series.{ext}", dpi=dpi)
        plt.close()


def export_panel_C_surrogates_of_j(ts: MiBiTimeSeries, j_id: str,
                                   example_surrogates: list[np.ndarray],
                                   out: Path, dpi: int = 300):
    """Overlay 3 IAAFT surrogates of j vs original j."""
    j = ts.biom.loc[j_id].values
    t = np.arange(ts.biom.shape[1])

    for ext in ("png", "svg"):
        plt.figure(figsize=(9, 3))
        for idx, s in enumerate(example_surrogates):
            plt.plot(t, s, lw=1.5, alpha=0.85, label=f"OTUj Surrogate {idx+1}", ls = "--")
        plt.plot(t, j, lw=2, color = "red", label="Original OTUj series")
        plt.xlabel("Time (aligned index)")
        plt.ylabel("CLR Relative Abundance")
        plt.title("IAAFT surrogates of OTUj (preserve spectrum & amplitude)")
        plt.legend()
        plt.tight_layout()
        plt.savefig(out / f"panel_C_surrogates_of_j.{ext}", dpi=dpi)
        plt.close()


def export_panel_D_surrogate_hist(rho_obs: float, surr_rhos: np.ndarray,
                                  n_surr: int, out: Path, dpi: int = 300):
    """Histogram of surrogate rho with observed line and two-tailed p."""
    p_two = two_tailed_p_from_surrogates(rho_obs, surr_rhos)

    for ext in ("png", "svg"):
        plt.figure(figsize=(6, 3))
        plt.hist(surr_rhos, bins=30, edgecolor="black")
        plt.axvline(rho_obs, lw=2, color="red", ls='--')
        plt.xlabel(r"Spearman $\rho$ (j$_t^{\rm surr}$ vs $\Delta$i$_{t+1}$)")
        plt.ylabel("Count (IAAFT surrogates of j)")
        plt.title(f"Surrogate test: ρ_obs={rho_obs:.2f}, p={p_two:.3g} (N={n_surr})")
        plt.tight_layout()
        plt.savefig(out / f"panel_D_surrogate_hist.{ext}", dpi=dpi)
        plt.close()

    # Save summary CSV for quick reference / captioning
    pd.DataFrame({
        "rho_obs": [rho_obs],
        "p_two_tailed": [p_two],
        "n_surrogates": [n_surr]
    }).to_csv(out / "panel_D_stats.csv", index=False)


def run_for_pair(biom_file: str, meta_file: str, i_id: str, j_id: str,
                 n_surr: int, n_iter: int, outdir: str, dpi: int, seed: int | None):
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)

    # Optional reproducibility
    if seed is not None:
        np.random.seed(seed)

    # Load
    biom_df = pd.read_csv(biom_file, index_col=0)
    biom_df.index = biom_df.index.astype(str).str.strip()
    i_id = str(i_id).strip()
    j_id = str(j_id).strip()
    meta_df = pd.read_csv(meta_file)

    # # Ensure IDs are strings to match DataFrame index typical dtype
    # i_id = str(i_id)
    # j_id = str(j_id)

    # Init timeseries object (it sorts columns by time internally)
    ts = MiBiTimeSeries(meta_df, biom_df)

    # Sanity checks
    if i_id not in ts.biom.index:
        raise ValueError(f"OTUi '{i_id}' not found in biom index.")
    if j_id not in ts.biom.index:
        raise ValueError(f"OTUj '{j_id}' not found in biom index.")

    # --- Observed rho (your lag_regress computes Spearman(j_t, Δi_{t+1}))
    rho_obs = ts.lag_regress(i_id, j_id, ts.biom)["rho"]

    # --- IAAFT surrogates on j (driver)
    ts.make_aaft_generator(j_id, silence_level=2)
    j_series = ts.biom.loc[j_id]
    surr_rhos = np.zeros(n_surr, dtype=float)
    example_surrogates: list[np.ndarray] = []

    for k in range(n_surr):
        surr = ts.generator.refined_AAFT_surrogates(n_iter, output="true_spectrum")
        j_surr = surr[0] if getattr(surr, "ndim", 1) > 1 else surr

        # Replace j with surrogate, compute TLC rho, then restore
        ts.biom_aaft.loc[j_id] = pd.Series(j_surr, index=j_series.index)
        surr_rhos[k] = ts.lag_regress(i_id, j_id, ts.biom_aaft)["rho"]
        ts.biom_aaft.loc[j_id] = j_series

        if k < 3:  # keep first 3 examples for panel C
            example_surrogates.append(np.asarray(j_surr).copy())

    # --- Export panels
    export_panel_B_time_series(ts, i_id, j_id, out, dpi=dpi)
    export_panel_C_surrogates_of_j(ts, j_id, example_surrogates, out, dpi=dpi)
    export_panel_D_surrogate_hist(rho_obs, surr_rhos, n_surr, out, dpi=dpi)

    # Also save a compact NPZ with arrays for reproducibility
    np.savez(out / "pair_data.npz",
             i_series=ts.biom.loc[i_id].values,
             j_series=ts.biom.loc[j_id].values,
             surr_rhos=surr_rhos,
             rho_obs=float(rho_obs),
             n_surr=int(n_surr),
             n_iter=int(n_iter))

    print(f"[OK] Saved panels + stats to {out.resolve()}")
    print(f"Observed rho = {rho_obs:.3f} | "
          f"two-tailed p = {two_tailed_p_from_surrogates(rho_obs, surr_rhos):.4g} "
          f"(N={n_surr}, IAAFT on j)")


def main():
    ap = argparse.ArgumentParser(description="Export poster panels for a specified OTU pair (i, j) using IAAFT on j.")
    ap.add_argument("--biom_file", required=True, help="CSV of OTU table (rows=OTUs, cols=epoch_time)")
    ap.add_argument("--meta_file", required=True, help="CSV of metadata with epoch_time column")
    ap.add_argument("--otu_j", required=True, help="Driver OTU id (e.g., 3609545)")
    ap.add_argument("--otu_i", required=True, help="Responder OTU id (e.g., 4346675)")
    ap.add_argument("--n_surr", type=int, default=500, help="Number of IAAFT surrogates for j (default: 500)")
    ap.add_argument("--n_iter", type=int, default=20, help="IAAFT refinement iterations (default: 20)")
    ap.add_argument("--outdir", default="panels_pair", help="Output directory (default: panels_pair)")
    ap.add_argument("--dpi", type=int, default=300, help="DPI for PNG (default: 300)")
    ap.add_argument("--seed", type=int, default=42, help="Optional numpy seed for reproducibility")
    args = ap.parse_args()

    run_for_pair(args.biom_file, args.meta_file,
                 args.otu_i, args.otu_j,
                 args.n_surr, args.n_iter, args.outdir, args.dpi, args.seed)


if __name__ == "__main__":
    main()