##editing timeseries_0619_update with Casey

import pandas as pd
import numpy as np
from scipy import stats # for spearman correlation
from pyunicorn.timeseries.surrogates import Surrogates #generate iaaft null-model surrogates
from copy import deepcopy
np.random.seed(42)  # set a random seed for reproducibility



class MiBiTimeSeries:
    def __init__(self, meta, biom):
        """
        Loads metadata, OTU abundance table, and phylogenetic tree. 
        Prunes OTU table to only include OTUs present in the tree as tips. 
        Sorts columns by epoch time to keep in chronological order.
        Keeps a list of the remaining otu IDs in self.nodes for easy looping

        Input: 
        meta: pandas DataFrame with metadata
        biom: pandas DataFrame (OTUs x epoch_time)
        """
        self.meta = meta

        #store a copy of the pruned biom table
        self.biom = biom

        # Ensure columns are integer epoch times, then sort by time order
        try:
            self.biom.columns = self.biom.columns.astype(int)
        except:
            pass
        
        #reorder the columns to be in ascending order of epoch time (column N is time t)
        self.biom = self.biom.reindex(sorted(self.biom.columns), axis=1)
        self.biom_shuffled = self.biom.copy()  # keep a copy of the shuffled biom table
        self.biom_aaft = self.biom.copy()  # keep a copy of the biom table for IAAFT surrogates
        #self._spear_rho_real = None  # to store the real Spearman rho value
        #self._null_distribution_shuffled = None  # to store the null distribution of Spearman correlations
        self.j_series = None  # to store the predictor series j for IAAFT surrogates
        self.generator = None  # to store the Surrogates generator for IAAFT surrogates
        #self._null_distribution_iaaft = None  # to store the null distribution of IAAFT surrogates

    def lag_regress(self, i, j, biom_df):
        """
        Spearman correlation between j(t) and the future change in i: Δi(t) = i(t+1) - i(t).
        Returns (i, j, rho, pvalue).
        """
        #Extract the CLR transformed values for i and j as pandas Series
        i_series = biom_df.loc[i]
        j_series = biom_df.loc[j]

        #pandas Series.shift(-1) gets the next value in the series, so we can compute the fwd change in i
        # drop the last value in i_series (NaN because there's no next value)
        delta_i = (i_series.shift(-1) - i_series).dropna()
        # pick j(t) at the same t as delta_i
        j_aligned = j_series.loc[delta_i.index]

        #compute spearman correlation between j(t) and Δi(t)
        rho, pval = stats.spearmanr(j_aligned, delta_i)

        #returns a tuple of (i, j, spearman_rho, and spearman pvalue - not yet adjusted for multiple testing)
        return {"rho":rho, "pval":pval}
    

    def shuffle_biom(self):
        """
        Randomly reorders the time signatures (columns) in the biom df.
        This simulates a null model where the time axis is shuffled but values for i and j remain intact.
        This is used for permutation tests to assess significance of lagged correlations.
        """
    
        self.biom_shuffled = self.biom_shuffled.reindex(
            columns=np.random.permutation(self.biom_shuffled.columns)
        )
    
    def get_spear_rho_real(self, i, j):
        """
        Computes the real Spearman correlation between i and j.
        This is used to compare against the null distributions generated by permutation tests.
        """
        # Call lag_regress to get the real Spearman rho for i and j
        self._spear_rho_real = self.lag_regress(i, j, self.biom)["rho"]
        
    
    def get_spear_rho_shuffled(self, i, j):
        """
        Computes the Spearman correlation between i and j after shuffling the time axis.
        This is used to generate a null distribution for permutation tests.
        """

        self.shuffle_biom()  # Shuffle the biom table
        result = self.lag_regress(i, j, self.biom_shuffled)

        return result["rho"]


    def gen_null_distribution_shuffled(self, i, j, precision=1e6):
        """
        Generates a null distribution of Spearman correlations by shuffling the time axis.
        Returns a list of Spearman rho values for the null distribution.
        """
        null_distribution_shuffled = []
        for _ in range(int(precision)):
            null_distribution_shuffled.append(self.get_spear_rho_shuffled(i, j))
        
        self._null_distribution_shuffled = np.array(null_distribution_shuffled)  # convert to numpy array for easier calculations


    def get_summary_stats_shuffled(self, i, j, precision=1e6):
        """
        Computes summary statistics for the null distribution of Spearman correlations.
        Returns a dictionary returning i, j, pseudo_pval, mean_rho_shuffled, mean_abs_rho_shuffled,
        spear_rho_real, precision.
        """

        # if self._spear_rho_real is None:
        self.get_spear_rho_real(i, j)  # compute the real Spearman rho if not already done
        # if self._null_distribution_shuffled is None:
        self.gen_null_distribution_shuffled(i, j, precision=precision)  # generate the null distribution if not already done

        abs_null_distribution_shuffled = np.abs(self._null_distribution_shuffled)  # take absolute values
        abs_spear_rho_real = abs(self._spear_rho_real)  # take absolute value of the observed correlation
        pseudo_pval_shuffled = 1 - stats.percentileofscore(abs_null_distribution_shuffled, abs_spear_rho_real) / 100
        mean_abs_rho_shuffled = np.mean(abs_null_distribution_shuffled)
        mean_rho_shuffled = np.mean(self._null_distribution_shuffled)
        spear_rho_real = self._spear_rho_real

        return {
            "i"                    : i,
            "j"                    : j,
            "pseudo_pval_shuffled" : pseudo_pval_shuffled,
            "mean_rho_shuffled"    : mean_rho_shuffled,
            "mean_abs_rho_shuffled": mean_abs_rho_shuffled,
            "spear_rho_real"       : spear_rho_real,
            "precision"            : precision
        }
    
    def make_aaft_generator(self, j, silence_level=2):
        """
        Computes the Spearman correlation between i and j using IAAFT surrogates.
        Returns a dictionary with i, j, pseudo_pval, null_distribution_iaaft.
        """
        self.j_series = self.biom.loc[j]
        j_array  = self.j_series.values[np.newaxis, :]
        self.generator = Surrogates(j_array, silence_level=silence_level)

    def gen_null_distribution_iaaft(self, i, j, precision=1e6, n_iterations=20):
        """
        Computes the Spearman correlation between i and j using IAAFT surrogates.
        Returns a dictionary with i, j, pseudo_pval, null_distribution_iaaft.
        """
        #if self.generator is None:
        self.make_aaft_generator(j)
        #if self.j_series is None:
        self.j_series = self.biom.loc[j]

        #list to collect each surrogate's spearman rho
        null_distribution_iaaft  = []
        for _ in range(int(precision)):
            #generate one power-spectrum-true surrogate series 
            surr = self.generator.refined_AAFT_surrogates(
                n_iterations, output="true_spectrum"
                )
            # returns either a 1xT or 2D array of surrogates
            # this line is just a failsafe to ensure we always get a 1D array
            checked_surr = surr[0] if surr.ndim > 1 else surr
            #overwrite j's row with the j IAAFT surrogate series
            self.biom_aaft.loc[j] = pd.Series(checked_surr, index=self.j_series.index)
            #record the surrogate rho value
            null_distribution_iaaft.append(self.lag_regress(i, j, self.biom_aaft)["rho"])
            #restore the real j series for the next iteration
            self.biom_aaft.loc[j] = self.j_series

        # convert the list of surrogate correlations to a numpy array for easier calculations
        self._null_distribution_iaaft = np.array(null_distribution_iaaft)

    def get_summary_stats_iaaft(self, i, j, precision=1e6, n_iterations=20):
        """
        Computes summary statistics for the null distribution of Spearman correlations using IAAFT surrogates.
        Returns a dictionary with i, j, pseudo_pval, mean_rho_iaaft, mean_abs_rho_iaaft,
        spear_rho_real, precision.
        """
        #if self._spear_rho_real is None:
        self.get_spear_rho_real(i, j)
        #if self._null_distribution_iaaft is None:
        self.gen_null_distribution_iaaft(i, j, precision=precision, n_iterations=n_iterations)

        abs_null_distribution_iaaft = np.abs(self._null_distribution_iaaft)  # take absolute values
        abs_spear_rho_real = abs(self._spear_rho_real)  # take absolute value of the observed correlation

        pseudo_pval_iaaft = 1 - stats.percentileofscore(abs_null_distribution_iaaft, abs_spear_rho_real) / 100
        mean_abs_rho_iaaft = np.mean(abs_null_distribution_iaaft)
        mean_rho_iaaft = np.mean(self._null_distribution_iaaft)
        spear_rho_real = self._spear_rho_real
        
        return {
            "i"                    : i,
            "j"                    : j,
            "pseudo_pval_iaaft"    : pseudo_pval_iaaft,
            "mean_rho_iaaft"       : mean_rho_iaaft,
            "mean_abs_rho_iaaft"   : mean_abs_rho_iaaft,
            "spear_rho_real"       : spear_rho_real,
            "precision"            : precision
        }